
/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loggers/wandb.py:389: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
┏━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃[1m   [22m┃[1m Name        [22m┃[1m Type             [22m┃[1m Params [22m┃
┡━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0 │ bert        │ BertModel        │ 89.1 M │
│ 1 │ classifiers │ ModuleList       │ 12.3 K │
│ 2 │ sigmoid     │ Sigmoid          │      0 │
│ 3 │ criterion   │ BCELoss          │      0 │
│ 4 │ metrics     │ MetricCollection │      0 │
└───┴─────────────┴──────────────────┴────────┘
[1mTrainable params[22m: 7.1 M
[1mNon-trainable params[22m: 82.0 M
[1mTotal params[22m: 89.1 M
[1mTotal estimated model params size (MB)[22m: 356
/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/fit_loop.py:293: The number of
training batches (26) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a
lower value for log_every_n_steps if you want to see logs for the training epoch.
[37mEpoch 0/3 [39m [35m━━━[90m╺━━━━━━━━━━━━━━━━━━━━━━━━[39m [37m3/26[39m [37m0:00:02 • 0:00:13[39m [37m1.79it/s[39m [37mv_num: ojgv train/loss:     











                                                                        [37m0.690                       


[37mValidation[39m [35m━━━━━━━━━━━━━━━━━━━━━━━[90m╺━━━[39m [37m6/7  [39m [37m0:00:03 • 0:00:01[39m [37m1.64it/s













                                                                        [37m0.684                       


[37mValidation[39m [35m━━━━━━━━━━━━━━━━━━━[90m╺━━━━━━━[39m [37m5/7  [39m [37m0:00:02 • 0:00:02[39m [37m1.83it/s












                                                                        [37m0.690                       


[37mValidation[39m [35m━━━━━━━━━━━━━━━━━━━━━━━[90m╺━━━[39m [37m6/7  [39m [37m0:00:03 • 0:00:01[39m [37m1.50it/s












                                                                        [37m0.686                       


[37mValidation[39m [35m━━━━━━━━━━━━━━━━━━━[90m╺━━━━━━━[39m [37m5/7  [39m [37m0:00:02 • 0:00:02[39m [37m1.80it/s
Epoch 3, global step 104: 'val_loss' reached 0.68868 (best 0.68868), saving model to '/content/drive/MyDrive/murata_labo_exp/murata_labo_exp_src/exp4/outputs/2023-11-16/05-38-18/wandb/run-20231116_053819-fuv0ojgv/files/checkpoints/epoch=3.ckpt' as top 1
`Trainer.fit` stopped: `max_epochs=4` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
実行済み
[37mTesting[39m [35m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[39m [37m4/4[39m [37m0:00:01 • 0:00:00[39m [37m2.48it/s
Error executing job with overrides: []
Traceback (most recent call last):
  File "/content/drive/MyDrive/murata_labo_exp/murata_labo_exp_src/exp4/main.py", line 434, in main
    trainer.test(model, data_module)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 754, in test
    return call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 794, in _test_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1028, in _run_stage
    return self._evaluation_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/evaluation_loop.py", line 141, in run
    return self.on_run_end()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/evaluation_loop.py", line 253, in on_run_end
    self._on_evaluation_epoch_end()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/evaluation_loop.py", line 329, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/content/drive/MyDrive/murata_labo_exp/murata_labo_exp_src/exp4/main.py", line 291, in on_test_epoch_end
    "test/confusion_matrix": plot.confusion_matrix(
  File "/usr/local/lib/python3.10/dist-packages/wandb/plot/confusion_matrix.py", line 63, in confusion_matrix
    assert max(preds) <= len(
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[?25h